apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.50-192.168.0.55
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kube-prom-stack
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.56-192.168.0.76
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool
  - kube-prom-stack
