apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume
  labels:
    volumeIdentifier: prometheus-server
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /opt/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: name
          operator: In
          values:
          - pi2
---